<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Moonlight.RingCT</AssemblyName>
    <RootNamespace>Moonlight.RingCT</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crypto\Crypto.csproj" />
    <ProjectReference Include="..\Serialization\Serialization.csproj" />
  </ItemGroup>

</Project>
