<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Moonlight.RingCT</AssemblyName>
    <RootNamespace>Moonlight.RingCT</RootNamespace>
    <Description>Pedersen commitments, ECDH, CLSAG, Bulletproofs+ and multi-exponentiation.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crypto\Crypto.csproj" />
    <ProjectReference Include="..\Serialization\Serialization.csproj" />
  </ItemGroup>

</Project>
