<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Moonlight.Wallet.Tests</AssemblyName>
    <RootNamespace>Moonlight.Wallet.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core.Http\Core.Http.csproj" />
    <ProjectReference Include="..\..\src\Core.Abi\Core.Abi.csproj" />
  </ItemGroup>

</Project>
