<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Moonlight.Serialization</AssemblyName>
    <RootNamespace>Moonlight.Serialization</RootNamespace>
    <Description>Transaction and block parsers, ids, Merkle root, Epee encoding.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crypto\Crypto.csproj" />
  </ItemGroup>

</Project>
