<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Moonlight.Wallet</AssemblyName>
    <RootNamespace>Moonlight.Wallet</RootNamespace>
    <Description>Keys, accounts, addresses, subaddresses, scanner, restore heights, encrypted storage.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RingCT\RingCT.csproj" />
    <ProjectReference Include="..\Node\Node.csproj" />
  </ItemGroup>

</Project>
