<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>moonlight</AssemblyName>
    <RootNamespace>Moonlight.Cli</RootNamespace>
    <PublishAot>true</PublishAot>
    <InvariantTimezone>true</InvariantTimezone>
    <ApplicationIcon>../../media/favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Wallet\Wallet.csproj" />
  </ItemGroup>

</Project>
